import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useMoralis } from "react-moralis";

const supportedChains = ["31337", "11155111"]; // localhost, sepolia

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {isWeb3Enabled ? (
                <div>
                    {supportedChains.includes(parseInt(chainId).toString()) ? (
                        <div>
                            <LotteryEntrance className="p-8" />
                        </div>
                    ) : (
                        <div>
                            <div className="h-70 grid grid-cols-7 gap-4 content-center">
                                <div className="col-start-3 col-span-3">
                                    <div className="p-1 text-center px-2 text-3xl">
                                        Please switch to a supported chain (Sepolia).
                                    </div>
                                </div>
                            </div>
                        </div>
                    )}
                </div>
            ) : (
                <div className="h-70 grid grid-cols-7 gap-4 content-center">
                    <div className="col-start-3 col-span-3">
                        <div className="p-1 text-center px-2 text-3xl">
                            Please connect to a Wallet
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
